apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: efk-logging
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform-tools/efk-logging/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: elasticsearch-master
      namespace: logging
    - apiVersion: apps/v1
      kind: Deployment
      name: kibana-kibana
      namespace: logging
    - apiVersion: apps/v1
      kind: DaemonSet
      name: fluent-bit
      namespace: logging
  timeout: 10m
  dependsOn:
    - name: sealed-secrets
