apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  path: ./platform-tools/karpenter/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karpenter-nodepool
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m              # ← add timeout
  path: ./platform-tools/karpenter/nodepool/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: karpenter