apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgC8iTokLHhKy5hTA08dwaBZkrr/3ptGFaMteeInUoQUSyxyg6mzHwz8phWUOQ1lugx2wezlnoaPwmA7eTgQqmbMX1n1CyQz3zGJGRBRbjk9P6TUsyQcMfz4G7n3Fl+gxpBkewHyqOyF0boJfzb0uX6lIBj7VWN+jgvS/bdufpAFwxJpYoN8bM/USOOfUjbK6X9FExKr1Q3XO1d1pW4lAWFQudE2NBrhUBhE328tf/1Rg+JZ3AvR507cIN9LEyGGK+mLptx1BYRucKFL3Fh15VECDMpYFOgZ2tKU9oOEroQ+EBnQ4IBQ2Moqd46HXo50PUIz4C1a8AaWNDDVJPeIgHqwgVlOQosSCueuH7f6u4B4AKxnsQhwe9fyycnv2VmlxPszxInZ7FHxi59vJBontMk3xXWdpF9cIbLMjgOhU1QC9QO8RnerI3XTMTD2NZuoXiE4dy9MF6wnpoJd5g19qxditrDXadjGXI+AX70Q2alByaquplMvA5F3OZywDt+IJ3YOS/dXUZ7WP5Fb9O4Zv/xolVpyM3cZMV+3N8SLNSIBzB2w/2ocX42rBjdmYhFJLm+fVdxFuOW7mneK9bj1d18OLo2x4VtRU195bqaCkSQqhg0z/P4JOT1IHy5j//Tq7qvQ0GblSvs11PEqBPneqODh3WMke+KD9x5VvSL7GaRGdM9gzQFYdgp2S9jqbZ+7j+92ifoO0RQV0fRMrlgpH+P0czSWPeuRKV3v8bGsvGEPVPUSqPJTCMAV3w9FPCWARLdRK+hqbFsG760H6NwJbCygDoOm4LDmAmtzRSIu5hXafV9Bt5yaflecs5DtX6j9IwGVGjBTqYjIi3D/J6aVxw==
  template:
    metadata:
      name: thanos-objstore-secret
      namespace: monitoring
