apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  values:
    replicaCount: 1

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 125m
        memory: 128Mi
