apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  values:
    replicas: 3
    minimumMasterNodes: 2

    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi

    volumeClaimTemplate:
      resources:
        requests:
          storage: 100Gi

    esJavaOpts: "-Xmx2g -Xms2g"

    antiAffinity: hard
