apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: portfolio-smtp
  namespace: {{ .Values.namespace.name | default "portfolio" }}
spec:
  encryptedData:
    SMTP_USER: __REPLACE_VIA_KUBESEAL__
    SMTP_PASS: __REPLACE_VIA_KUBESEAL__
    RECIPIENT_EMAIL: __REPLACE_VIA_KUBESEAL__
  template:
    metadata:
      name: portfolio-smtp
      namespace: {{ .Values.namespace.name | default "portfolio" }}
    type: Opaque
