# platform-tools/velero/overlays/dev/patch.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    upgradeCRDs: false        # ← skip the problematic job entirely
    kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: "latest"
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: 372517046622-velero-backups-dev
          config:
            region: us-east-1
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: us-east-1
    schedules:
      daily-backup:
        schedule: "0 22 * * *"
        template:
          ttl: 168h
          includedNamespaces:
            - monitoring
            - karpenter
            - flux-system