apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m
  chart:
    spec:
      chart: velero
      version: "8.x.x"        # ← pin to specific version e.g. "8.1.0"
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::372517046622:role/velero-role

    configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: 372517046622-velero-backups-dev
          config:
            region: us-east-1
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: us-east-1

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.0    # ← v1.11.x matches velero v1.15.x
        volumeMounts:
          - mountPath: /target
            name: plugins