apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m

  chart:
    spec:
      chart: velero
      version: "8.1.0"
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system

  values:

    upgradeCRDs: true

    kubectl:
      image:
        repository: registry.k8s.io/kubectl
        tag: v1.30.0

    serviceAccount:
      server:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::372517046622:role/velero-role

    configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: 372517046622-velero-backups-dev
          config:
            region: us-east-1

      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: us-east-1

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins