apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-certs
  namespace: logging
  labels:
    app.kubernetes.io/managed-by: flux
type: Opaque
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
