apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kibana-kibana-es-token
  namespace: logging
spec:
  encryptedData:
    token: AgBWUHv+RoZ4WaRgaU9k9VfzS2lLD67PxQZcr/CzvCA2JgtGRy20thpaEDilvVmGGl4l7wB+/tdTSDkv4BA5CIV4aaxzI0Ej9Lsmku0JPdxpdq/aJjhUvp1zZlCSVCOtWvB9VBnDyeEZHwOUOD+soLmyAm6YfIR0y2p0/Y6xArd/ibRxrc+w1LS/92tG7Enz8+Px6EBbH4wtsV8TVnRWeGGDIFyQWCwNKcJKWzxRQ1QNAW4a6+tFKbw8R5gtVfVivx2d+wN9wJZZZhLWO493Y/5nmIB4kIhiOvzS7xJzznpUnGD45HGFLM2RCaupYGgyvwr3hKApNREJitXr4U7YnEmQdVMOzexJrriMeCiRHSRb4A0UvtKgXPbfCStTOxbjC8g4R++bImLD0E1r0bOaSBd/iuSQtUwJjwAwn3XOnG1VvStPmWZ22xxsLUbEcgvxAtFja4FgtaBKBYeODVewsR5WI+TfayOoTcenGcPFfCAXKtBcDy6ap8MatQIhG5XAl2+U76ZEKo9hoTQVC/JofsgEBFniYnKFmpmqtfF6ccycRRWCHSZltlz08/Uw+3Zkg/MUa4XhcEFrmidWCJDDXgjVLGQYWC6HNxK+hbwFsQikcxQ3U2hELujS5CQ6BCIHZR0VZF1aBOZ7SVRsEql8kXPUQg7Cl28ln5UKZHzHdQ5FY9Oi5uAzyA2gbEpYsUM3ZdY=
  template:
    metadata:
      name: kibana-kibana-es-token
      namespace: logging
