apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository-elastic.yaml
  - helmrepository-fluent.yaml
  - helmrelease-elasticsearch.yaml
  - helmrelease-kibana.yaml
  - helmrelease-fluentbit.yaml
  - networkpolicy.yaml
