apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: portfolio-web
  namespace: flux-system
spec:
  image: 372517046622.dkr.ecr.us-east-1.amazonaws.com/portfolio-web
  interval: 5m
  provider: aws
