apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*.yedressov.com"
        - "yedressov.com"
