apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portfolio
  namespace: portfolio
spec:
  interval: 10m
  chart:
    spec:
      chart: portfolio
      sourceRef:
        kind: HelmRepository
        name: ecr-charts
        namespace: flux-system
  values:
    namespace:
      name: portfolio

    replicas:
      api: 2
      web: 2

    images:
      api: 372517046622.dkr.ecr.us-east-1.amazonaws.com/portfolio-api:PLACEHOLDER # {"$imagepolicy": "flux-system:portfolio-api"}
      web: 372517046622.dkr.ecr.us-east-1.amazonaws.com/portfolio-web:PLACEHOLDER # {"$imagepolicy": "flux-system:portfolio-web"}

    ports:
      api: 5000
      web: 3000

    api:
      url: "http://portfolio-api.portfolio.svc.cluster.local:5000"

    config:
      allowedOrigins: "https://yedressov.com,http://localhost:3000"
      rateLimit: "5"
      rateWindowMinutes: "15"
      maxBodyBytes: "16384"

    serviceAccount:
      api: portfolio-api
      web: portfolio-web

    resources:
      api:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      web:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
