apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portfolio
  namespace: portfolio
spec:
  interval: 10m
  chart:
    spec:
      chart: portfolio
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: ecr-charts
        namespace: flux-system
  values:
    namespace:
      name: portfolio

    replicas:
      api: 2
      frontend: 2

    images:
      api: 372517046622.dkr.ecr.us-east-1.amazonaws.com/portfolio-api:42476509714ae08c779e1d7190d8842e0dfba1c5
      frontend: 372517046622.dkr.ecr.us-east-1.amazonaws.com/portfolio-web:42476509714ae08c779e1d7190d8842e0dfba1c5

    ports:
      api: 8000
      frontend: 3000

    api:
      url: "http://portfolio-api.portfolio.svc.cluster.local:8000"

    resources:
      api:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      frontend:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
