name: CI for Docker images

on:
    push:
        branches:
          - main
        paths:
          - 'app/**'
    pull_request:
        branches:
          - main
        paths:
          - 'app/**'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
    publish-images:
        runs-on: ubuntu-22.04

        steps:
        # 1 Checkout repo
        - name: Checkout Repository
          uses: actions/checkout@v4

        # 2 Login to AWS Role
        - name: Login to AWS Role
          uses: aws-actions/configure-aws-credentials@v5.1.1
          with:
            aws-region: us-east-1
            role-to-assume: ${{ vars.IAM_ROLE }}
            role-session-name: gha-login-session

        # 3 Login to Amazon ECR
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        # 4 Configure short SHA tag
        - name: Configure short SHA tag
          run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

        # 5 Build, scan, and conditionally push backend docker image
        - name: Backend - Build docker image
          working-directory: ./app/backend/
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: images/portfolio-backend
          run: docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

        - name: Backend - Trivy vulnerability scan
          uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
          env:
            TRIVY_VERSION: 'v0.69.3'
          with:
            image-ref: '${{ steps.login-ecr.outputs.registry }}/images/portfolio-backend:${{ env.IMAGE_TAG }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            severity: 'CRITICAL,HIGH'
            scanners: 'vuln'

        - name: Backend - Push docker image to ECR
          if: github.ref == 'refs/heads/main'
          working-directory: ./app/backend/
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: images/portfolio-backend
          run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

        # 6 Build, scan, and conditionally push frontend docker image
        - name: Frontend - Build docker image
          working-directory: ./app/frontend/
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: images/portfolio-frontend
          run: docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

        - name: Frontend - Trivy vulnerability scan
          uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
          env:
            TRIVY_VERSION: 'v0.69.3'
          with:
            image-ref: '${{ steps.login-ecr.outputs.registry }}/images/portfolio-frontend:${{ env.IMAGE_TAG }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            severity: 'CRITICAL,HIGH'
            scanners: 'vuln'

        - name: Frontend - Push docker image to ECR
          if: github.ref == 'refs/heads/main'
          working-directory: ./app/frontend/
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: images/portfolio-frontend
          run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
